fail_fast: true

repos:
  - repo: local
    hooks:
      - id: system
        name: mypy
        entry: poetry run mypy .
        pass_filenames: false
        language: system
      - id: system
        name: black
        entry: poetry run black --check .
        pass_filenames: false
        language: system
