fail_fast: true

repos:
  - repo: local
    hooks:
      - id: system
        name: mypy
        entry: poetry run mypy
        language: system
        types: [file, python]
      - id: system
        name: black
        entry: poetry run black --check
        language: system
        types: [file, python]
