version: "3.2"
services:
  pgdb:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: database
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
