[tool.poetry]
name = "polynomial"
version = "0.1.0"
description = ""
authors = ["Olivier Corradi <olivier.corradi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1.4"
requests = "^2.28.1"
django-jsonform = "^2.15.0"
oauthlib = "^3.2.2"
environs = {extras = ["django"], version = "^9.5.0"}
gunicorn = "^20.1.0"
psycopg2-binary = "^2.9.5"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
black = "^22.12.0"
isort = "^5.11.2"
django-stubs = "^1.13.1"
mypy = "^0.991"
types-requests = "^2.28.11"
types-psycopg2 = "^2.9.21"
types-oauthlib = "^3.2.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
